language: ruby
bundler_args: --without debugging guard
script: bundle exec rake spec:ci
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
  - ree
  - topaz
matrix:
  allow_failures:
    - rvm: topaz
